### ISSUE TITLE
Any way to set a hint?

### ISSUE THREAD

**Issue by jaredsburrows** [BertrandBev/code_field#79]

**Comment by mack-at-pieces** [comment]
@jaredsburrows I have a branch for this, but @BertrandBev I need write permissions to push my branch to the origin and create a PR

**Comment by BertrandBev** [comment]
@mack-at-pieces have you tried to create a fork, push to your fork and then open up a PR? That should work just fine

**Comment by mack-at-pieces** [comment]
@BertrandBev wasn't sure how that would play out since I already had a fork with updates on it's master branch, but seems to have worked out just fine 👍🏼 #80

**Comment by BertrandBev** [comment]
Great, thanks @mack-at-pieces !

**Comment by jaredsburrows** [comment]
@BertrandBev When will this be released?

**Comment by BertrandBev** [comment]
Not sure, do you need it soon?

**Comment by jaredsburrows** [comment]
No rush just nice to have. "Type your code here".


Jared Burrows

***@***.***
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Comment by mack-at-pieces** [comment]
@jaredsburrows just add this to your `pubspec.yaml` as the code_field dependency until it's updated on pub.dev

```
code_field:
  git: 
    url: https://github.com/BertrandBev/code_field
    ref: 59ae52ab3e6f8de0db4b00cfe637e89d6dd2decb
```

**Comment by jaredsburrows** [comment]
Thank you @mack-at-pieces.

I got it working with:
```yaml
dependencies:
#  code_text_field: ^1.1.0 # https://pub.dev/packages/code_text_field
  code_text_field:
    git:
      url: https://github.com/BertrandBev/code_field
      ref: 59ae52ab3e6f8de0db4b00cfe637e89d6dd2decb
```

I'll revert it back hen it is officially released.
